parameters:
#    spiralation_ngo.example.class: Spiralation\NGOBundle\Example

services:
#    spiralation_ngo.example:
#        class: %spiralation_ngo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
