homeO:
    pattern:  /home
    defaults: { _controller: SpiralationUserBundle:Home:organization }

homeV:
    pattern:  /home
    defaults: { _controller: SpiralationUserBundle:Home:volunteer }
    
profileV:
    pattern:  /profile
    defaults: { _controller: SpiralationUserBundle:Profile:volunteer }