parameters:
#    spiralation_user.example.class: Spiralation\UserBundle\Example

services:
#    spiralation_user.example:
#        class: %spiralation_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
