parameters:
#    spiralation_styles.example.class: Spiralation\StylesBundle\Example

services:
#    spiralation_styles.example:
#        class: %spiralation_styles.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
