parameters:
#    spiralation_site.example.class: Spiralation\SiteBundle\Example

services:
#    spiralation_site.example:
#        class: %spiralation_site.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
